
name: Linter

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON: true
